development:
  adapter: postgresql
  encoding: unicode
  database: intro_demo_alt_dev
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: intro_demo_alt_prod
  pool: 2
  username: your_username
  password: your_password
